kind: Job
apiVersion: batch/v1
metadata:
  name: safegan-training
  labels:
    model: safegan
    team: flora
spec:
  backoffLimit: 0  # Do never retry!
  template:
    metadata:
      labels:
        model: safegan
        team: flora
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: read-datasets-pvc
        - name: git-repo
          emptyDir: {}
      initContainers:
        - name: git-clone
          image: alpine/git
          args:
            - clone
            - -b
            - master
            - --
            - https://2073fc7ced25efec5b326e5dde5176a6f96dcf00@cc-github.bmwgroup.net/adp/adp.git
            - /repo
          volumeMounts:
            - mountPath: /repo
              name: git-repo
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      containers:
        - name: safe-gan-flora
          image: cc-artifactory.bmwgroup.net/adp-mlfusion/flora:latest
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: "/data"
              name: data-volume
            - mountPath: "/repo"
              name: git-repo
          env:
            - name: "PYTHONPATH"
              value: "/repo"
          command: ["/bin/bash"]
          tty: true
      imagePullSecrets:
        - name: flora
      restartPolicy: Never

